name: CI Build (Linux - GCC & Clang)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang

      - name: Build formatter_lib
        run: |
          mkdir -p formatter_lib/build && cd formatter_lib/build
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ ..
          cmake --build .

      - name: Build formatter_ex_lib
        run: |
          mkdir -p formatter_ex_lib/build && cd formatter_ex_lib/build
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ -Dformatter_DIR=../formatter_lib/build ..
          cmake --build .

      - name: Build solver_lib
        run: |
          mkdir -p solver_lib/build && cd solver_lib/build
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ -Dformatter_ex_DIR=../formatter_ex_lib/build ..
          cmake --build .

      - name: Build applications
        run: |
          # Hello World
          mkdir -p hello_world_application/build && cd hello_world_application/build
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ -Dformatter_ex_DIR=../../formatter_ex_lib/build ..
          cmake --build .
          
          # Solver App
          mkdir -p solver_application/build && cd solver_application/build
          cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ -Dformatter_ex_DIR=../../formatter_ex_lib/build -Dsolver_lib_DIR=../../solver_lib/build ..
          cmake --build .

      - name: Run tests
        run: |
          ./hello_world_application/build/hello_world
          ./solver_application/build/solver_application
