name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential clang
        
    - name: Set up compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
        else
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
        fi
        
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_C_COMPILER=${{ env.CC }} \
          -DCMAKE_CXX_COMPILER=${{ env.CXX }}
          
    - name: Build
      run: |
        cmake --build build --config ${{ matrix.build_type }} --parallel 2
        
    - name: Run tests
      run: |
        cd build && ctest --output-on-failure

  windows_build:
    name: Windows (${{ matrix.build_type }})
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build project
      run: |
        cmake --build build --config ${{ matrix.build_type }} --parallel 2

    - name: Find binaries location
      id: find_binaries
      shell: pwsh
      run: |
        $solverPath = Get-ChildItem -Path build -Recurse -Filter "solver_application.exe" | Where-Object { $_.DirectoryName -match "\\${{ matrix.build_type }}\\" } | Select-Object -First 1 -ExpandProperty FullName
        $helloPath = Get-ChildItem -Path build -Recurse -Filter "hello_world.exe" | Where-Object { $_.DirectoryName -match "\\${{ matrix.build_type }}\\" } | Select-Object -First 1 -ExpandProperty FullName
        
        if (-not $solverPath) { throw "solver_application.exe not found in ${{ matrix.build_type }} configuration" }
        if (-not $helloPath) { throw "hello_world.exe not found in ${{ matrix.build_type }} configuration" }
        
        Write-Output "solver_path=$solverPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        Write-Output "hello_path=$helloPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Run applications
      shell: pwsh
      run: |
        "1 -5 6" | & "${{ steps.find_binaries.outputs.solver_path }}"
        & "${{ steps.find_binaries.outputs.hello_path }}"
