name: CI Build (Linux - GCC & Clang)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ gcc, clang ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential clang

      - name: Prepare build
        run: |
          mkdir -p build
          ls -R  # Для отладки структуры

      - name: Configure
        working-directory: ./build
        run: |
          cmake \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++ \
            -Dformatter_lib_SOURCE_DIR=../formatter_lib \
            -Dformatter_ex_lib_SOURCE_DIR=../formatter_ex_lib \
            -Dsolver_lib_SOURCE_DIR=../solver_lib \
            ../

      - name: Build
        working-directory: ./build
        run: |
          cmake --build . --target formatter formatter_ex solver_lib
          cmake --build . --target hello_world_application solver_application

      - name: Run tests
        run: |
          ./build/hello_world_application/hello_world
          ./build/solver_application/solver_application
