name: CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux_build:
    name: Linux (${{ matrix.compiler }} - ${{ matrix.build_type }})
    strategy:
      matrix:
        compiler: [gcc, clang]
        build_type: [Debug, Release]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential clang
        
    - name: Set up compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV
        else
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
        fi
        
    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_C_COMPILER=${{ env.CC }} \
          -DCMAKE_CXX_COMPILER=${{ env.CXX }}
          
    - name: Build
      run: |
        cmake --build build --parallel 2
        
    - name: Run tests
      run: |
        cd build && ctest --output-on-failure

  windows_build:
    name: Windows (${{ matrix.build_type }})
    strategy:
      matrix:
        build_type: [Debug, Release]
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build project
      run: |
        cmake --build build --config ${{ matrix.build_type }} --parallel 2

    - name: Run applications
      run: |
        echo "1 -5 6" | .\build\solver_application\${{ matrix.build_type }}\solver_app.exe
        .\build\hello_world_application\${{ matrix.build_type }}\hello.exe
